# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: (Auto) Generate Release Image

on:
  push:
    tags:
      - v*

env:
  ARTIFACTORY_DOCKER_REGISTRY: ${{ vars.ARTIFACTORY_DOCKER_REGISTRY }}
  ARTIFACTORY_DOCKER_REPO: ${{ vars.ARTIFACTORY_DOCKER_REPO }}
  HELM_REPO: ${{ vars.HELM_REPO }}
  TAG_NAME: ${{ github.ref_name }}
  VAULT_ADDRESS_PROD: ${{ vars.VAULT_ADDRESS_PROD }}
  VAULT_GITHUB_ROLE: ${{ vars.VAULT_GITHUB_ROLE }}
  VAULT_GITHUB_PATH: ${{ vars.VAULT_GITHUB_PATH }}
  vars: ${{ toJSON(vars) }}
  language: python
  
jobs:
  build_image:
    permissions:
      contents: read
      id-token: write
    runs-on:
      - ${{ vars.IMAGE_BUILD_RUNNER }}
    container:
      image: "${{ vars.KANIKO_IMAGE }}"
      credentials:
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
    - name: Build image
      uses: kering-technologies-china/dso-cus-github-action/microservice/kaniko-build@main
      id: kaniko_build
      with:
        tag: ${{ env.TAG_NAME }}
        python-base-image: "python:3.11-slim"
    - name: Jfrog scan image
      uses: kering-technologies-china/dso-cus-github-action/jfrog-scan@main
      with:
        target: "${{ env.projectName }}.${{ env.tag }}.tar"