# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: (Manual) Create Release

on: workflow_dispatch
  
run-name: Create release from ${{ github.sha }}

env:
  ARTIFACTORY_DOCKER_REGISTRY: ${{ vars.ARTIFACTORY_DOCKER_REGISTRY }}
  ARTIFACTORY_DOCKER_REPO: ${{ vars.ARTIFACTORY_DOCKER_REPO }}
  HELM_REPO: ${{ vars.HELM_REPO }}
  VAULT_ADDRESS_PROD: ${{ vars.VAULT_ADDRESS_PROD }}
  VAULT_GITHUB_ROLE: ${{ vars.VAULT_GITHUB_ROLE }}
  VAULT_GITHUB_PATH: ${{ vars.VAULT_GITHUB_PATH }}
  vars: ${{ toJSON(vars) }}
  language: python

jobs:
  create_branch:
    permissions: 
      contents: read
      id-token: write
    runs-on:
      - kt-gu-cn
    steps:
      - name: Generate GitHub App Token
        id:  app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.GH_ACTIONS_CUS_APP_ID }}
          private_key: ${{ secrets.GH_ACTIONS_CUS_PRIVATE_KEY }}          
      - uses: kering-technologies-china/dso-cus-github-action/microservice/setup-env@main
        name: Setup Environment
      - uses: actions/checkout@v4
        with:
          token: ${{ steps. app_token.outputs.token }}   # Github App Token
      - uses: kering-technologies-china/dso-cus-github-action/create-release-branch@main
        name: Create release branch
        id: create_release_branch
      - name: Display release branch name
        run: |
          echo "the new release branch name is ${{ steps.create_release_branch.outputs.release_branch_name}}."
          echo "the create release branch result is ${{ steps.create_release_branch.outputs.branch_result}}."